name: Build Docker Images
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.NadzeyaS }}
          password: ${{ secrets.dckr_pat_7xyPr3_lncF-EoQK1b9SF0s8ucQ}}

      - name: Build and push Docker image (x86_64)
        run: |
          docker buildx build --platform linux/amd64 --push -t your-username/your-image:latest .
      
      - name: Build and push Docker image (arm64)
        run: |
          docker buildx build --platform linux/arm64 --push -t your-username/your-image:latest .
