name: Push Docker Image to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Packages
        run: echo "${{ secrets.GHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 --push -t ghcr.io/walicce/walicce/zadanie2:${{ github.sha }} .

      - name: Create package
        id: create_package
        run: |
          response=$(curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/user/packages")
          package_id=$(echo "$response" | jq -r '.id')
          echo "::set-output name=package_id::$package_id"

      - name: Add package to repository
        run: |
          package_id=${{ steps.create_package.outputs.package_id }}
          repository_name=zadanie2
          curl -X PUT \
            -H "Authorization: Bearer ${{ secrets.GHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/user/packages/packages/$package_id/repository" \
            -d "{\"package_name\":\"my-package\"}"


