name: Build Docker Images
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHUB_USERNAME }}
          password: ${{ secrets.GHUB_TOKEN}}

      - name: Build and push Docker image (x86_64)
        run: |
          docker buildx build --platform linux/amd64 --push -t ghcr.io/walicce/zadanie2:latest .
      
      - name: Build and push Docker image (arm64)
        run: |
          docker buildx build --platform linux/arm64 --push -t ghcr.io/walicce/zadanie2:arm64-latest .
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_CLI_EXPERIMENTAL: enabled
          DOCKER_BUILDKIT_INLINE_CACHE: 1
